### ISSUE TITLE
No binaries

### ISSUE THREAD

**Issue by KahanPrabhu** [SoftwareEngineeringToolDemos/ICSE-2011-Bug-Query-Language#2]

**Comment by KahanPrabhu** [comment]
The only URL mentioned in the paper doesn't work. The authors weren't helpful either, since they replied to none of my mails. Hence no binaries.

**Comment by CaptainEmerson** [comment]
Please edit your comment (and any other similar ones). Be respectful to the authors.

**Comment by KahanPrabhu** [comment]
The URL mentioned in the paper doesn't work. I tried emailing the authors for help, but they couldn't get back to me.
